### ISSUE TITLE
How to use fetch

### ISSUE THREAD

**Issue by tzuriely** [cullenjett/react-ssr-boilerplate#10]
Hi,
I am trying to make actions with "fetch" from my API and update the store, and at the end to render.
I failed to find the right way to do that

**Comment by cullenjett** [comment]
Hey @tzuriely, if you're asking about how to do that in general I would check out the Redux documentation for [async action creators[(https://redux.js.org/advanced/async-actions#async-action-creators). This project is already configured to use `redux-thunk` (which that documentation mentions), so you should be able to follow along with their examples pretty closely.

If you're trying to fetch **on the server** and wait to send a response to the client until that fetch is complete that can be done by using a `static fetchData()` method on a component **that is rendered by the router**. Check out [the Home component](https://github.com/cullenjett/react-ssr-boilerplate/blob/master/src/components/Home.js#L6) for an example. You then have to add matching `react-router` config to [the `fetchDataForRender()` function](https://github.com/cullenjett/react-ssr-boilerplate/blob/master/server/fetchDataForRender.js#L6) on the server so it knows to call that component's `fetchData()` method. It's not ideal, and eventually I'll add logic to walk the component tree and call any `static fetchData()` methods in that tree, but for now it has to be the "top level" component being rendered.

**Comment by LukeWalker1996** [comment]
Hey @cullenjett , thank you so much for such a great repo! I've been working on a project now for several weeks that uses this repo, and what a breeze its been. I have a question relating to your comment above; specifically: 

> "You then have to add matching react-router config to the fetchDataForRender() function on the server so it knows to call that component's fetchData() method."

I've looked at both [fetchDataForRender.js](https://github.com/cullenjett/react-ssr-boilerplate/blob/master/server/fetchDataForRender.js) and [renderServerSideApp.js](https://github.com/cullenjett/react-ssr-boilerplate/blob/master/server/renderServerSideApp.js) and i can see whats going on, however, i still don't understand how or where to place the matching config as described above. 

Could you possibly explain how this would work?

I have multiple routes which call the fetchData method, so an example with more than one route would be very advantageous.

Thank you.

**Comment by cullenjett** [comment]
Hi @LukeWalker1996, I'm glad to hear this has been helpful!

Do you know roughly when you pulled this repo? In June I [released an update](https://github.com/cullenjett/react-ssr-boilerplate/blob/master/CHANGELOG.md#400---2019-06-09) that changed how this project fetches data on the server. It used to only be able to fetch on the server for top-level react-router routes and needed some duplicate config to handle that appropriately, but now any component in the tree can trigger a fetch on the server without that extra config in `fetchDataForRender.js`. [Here's a diff](https://github.com/cullenjett/react-ssr-boilerplate/compare/v3.0.1..master) of v3.0.1 to the current code if you want to see what changed there.

This issue (any my response) are related to the old version, so to answer your question it's no longer necessary. If you have the "new" version and are having trouble getting server fetching to work I'd be happy to offer whatever guidance I can if you share some details (maybe open a new issue if you don't mind).
