### ISSUE TITLE
webpack for production server

### ISSUE THREAD

**Issue by sinwailam193** [cullenjett/react-ssr-boilerplate#13]
Hi according to this post, babel-register is not for production use: https://github.com/babel/babel/issues/5851. Currently, in server/index.js it is using @babel/register. Will there be plans to integrate a production webpack server build in the future?

**Comment by cullenjett** [comment]
It's definitely on my todo list. 

If you're itching to see what it'll take to do I have a [WIP branch](https://github.com/cullenjett/react-ssr-boilerplate/tree/server-bundle) going that technically works. It's super ugly and almost certainly not what the final result will look like, but it shows the general idea.
