### ISSUE TITLE
Wrong MIME type when build for prod (css&js)

### ISSUE THREAD

**Issue by pavelprokes** [cullenjett/react-ssr-boilerplate#2]
Hi! I'll use your boilerplate. When I do `npm run build && npm run start-prod` paths of css and script has wrong mime type and page not render correctly.

Package.json is the same as your.

Can you help me?

Thank you
Pavel

![screen shot 2018-04-08 at 10 31 20](https://user-images.githubusercontent.com/16275047/38465087-05666740-3b18-11e8-80df-e95f9c971da5.png)
![screen shot 2018-04-08 at 10 31 10](https://user-images.githubusercontent.com/16275047/38465089-05825b76-3b18-11e8-9512-034dd38089cd.png)

**Comment by cullenjett** [comment]
Sure, tell me a little more about what you've changed (if anything). Also what does your `build/` directory look like?
