### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by chetank628** [cullenjett/react-ssr-boilerplate#20]
I tried implementing the controller model in  the express server it works fine  when I run in dev mode as soon as I build and run in production mode it gives me the following error

what I have added is just one controllers folder with api.js and index.js file and one routes folder with routes.js file and by using app.use I am injecting the code in the main express file
```
Error: Cannot find module 'server/routes/api.js'
    at l (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:205018)
    at /Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:3399
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:3374)
    at Object.<anonymous> (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:3434)
    at l (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:124)
    at Module.<anonymous> (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:204211)
    at Module.<anonymous> (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:204621)
    at l (/Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:124)
    at /Users/chetan/Documents/repos/SSR/react-ssr-boilerplate-master/build/server.js:1:924
```

the app.js file contains the following code 
```
import path from 'path';
import express from 'express';
import compression from 'compression';
import helmet from 'helmet';
import morgan from 'morgan';
import responseTime from 'response-time';
import routes from './routes';


import { renderServerSideApp } from './renderServerSideApp';

// This export is used by our initialization code in /scripts
export const app = express();
const { PUBLIC_URL = '' } = process.env;

app.use(routes);
app.use(compression());
app.use(helmet());

// Serve generated assets
app.use(
  PUBLIC_URL,
  express.static(path.resolve(__dirname, '../build'), {
    maxage: Infinity
  })
);

// Serve static assets in /public
app.use(
  PUBLIC_URL,
  express.static(path.resolve(__dirname, '../public'), {
    maxage: '30 days'
  })
);

app.use(morgan('tiny'));

app.use(
  responseTime((_req, res, time) => {
    res.setHeader('X-Response-Time', time.toFixed(2) + 'ms');
    res.setHeader('Server-Timing', `renderServerSideApp;dur=${time}`);
  })
);

app.use(renderServerSideApp);
```

**Comment by cullenjett** [comment]
Hey @chetank628,

Based on your description you have a directory structure like this:

```
- server/
  - controllers/
    - index.js
    - api.js
  - routes/
    - routes.js
```

but the error message you posted says it can't find a module at `/server/routes/api.js`, which doesn't exist (assuming the structure above is correct). Is it possible you have an invalid import/require statement somewhere?

I can help you debug it if you point me to your full code, or at least the other files you've added in the `server/` directory (`controllers/index`, `controllers/api`, and `routes/routes`).

**Comment by chetank628** [comment]
```
Folder Structure is like this 
- server/
  - controllers/
    - index.js
    - api.js
  - routes/
    -api.js
    -index.js

```
sorry I meant api.js not routes api.js which contain routes
it is working in dev mode and not after building it for prod find the project below
![Screenshot 2019-06-19 at 1 46 56 AM](https://user-images.githubusercontent.com/10745374/59716878-6ad7e800-9234-11e9-9e82-73b1147453cc.png)
 
[react-ssr-boilerplate-master 2.zip](https://github.com/cullenjett/react-ssr-boilerplate/files/3303237/react-ssr-boilerplate-master.2.zip)

**Comment by cullenjett** [comment]
I _think_ the primary issue might be from the use of `fs` to dynamically `require` files. I haven't done it in this setup so I don't have a concrete answer on how to fix your issue, but you could try replacing those dynamic `require`s in your `index` files with individual `require` (or `import`) statements.

When the server runs in development mode it's transpiled on the fly with babel-register (see `scripts/start.js`), but the production build is run through webpack and ends up in a single bundle file (see `build/server.js`). My thought is that webpack isn't configured to allow that for the production server bundle, so the answer could be a missing plugin or setting for `config/webpack.config.prod.js`.

I'm also curious if there's an issue with mixing `import` and `module.exports` in the same file, so if you still see issues with explicit `require` calls then I'd try using only es6 (`import` and `export`) or commonjs (`require` and `module.exports`) module format in a file.
