### ISSUE TITLE
Css issues

### ISSUE THREAD

**Issue by lineldcosta** [cullenjett/react-ssr-boilerplate#4]
Hello nice boilerplate, copied many things from this :-P

Actually i got one issue, if i import css files in app.js, then  while running npm run start-prod it will not parse css files.

**Comment by cullenjett** [comment]
Thanks for checking out the project!

Unfortunately, not being able to use CSS modules is a known limitation of the current architecture, see [this closed issue](https://github.com/cullenjett/react-ssr-boilerplate/issues/3) for more information.

**Comment by lineldcosta** [comment]
Just added server side webpack template on the top of this code. everything works fine :-)
