### ISSUE TITLE
Cannot install packgaes

### ISSUE THREAD

**Issue by vndevil** [cullenjett/react-ssr-boilerplate#6]
When I download source code and run 'npm install', It's has this error: node-pre-gyp install --fallback-to-build.

Any help to fix this issue?
Many thanks

**Comment by cullenjett** [comment]
I bumped my local Node version to 10.8 and was able to reproduce a similar installation issue, so I just pushed up v2.8.0 that replaces `shrink-ray` with `compression` in an effort to support more Node versions. It's not quite as baller, but it works.
