### ISSUE TITLE
Issue with server side rendering ClassName

### ISSUE THREAD

**Issue by pruthvip** [cullenjett/react-ssr-boilerplate#7]
Hi,
Thanks for this boilerplate. It helped a lot.
 while using i came across an issue, whenever I add a new class to any div. I get the following error

`warning.js:33 Warning: Prop `className` did not match. Server: "null" Client: "top-content__sub-points__item"`

But when i kill the server and start again, this gets resolved , and the class gets applied.

Is there any thing which I am missing?

**Comment by cullenjett** [comment]
Nope, looks like a bug, thanks for bringing it up. I know I've had to fix this before (somewhere), so I'll try to take a look soon.

In the meantime it'll be pretty annoying during development, but in production the SSR should be OK.

**Comment by pruthvip** [comment]
Thanks @cullenjett .

**Comment by cullenjett** [comment]
Alright, I just pushed up version 2.8.1 with what I hope is a fix for this issue. [Here's the commit](https://github.com/cullenjett/react-ssr-boilerplate/commit/4869e63b57ec59e66a58e9559aafd9b2c4ebfc34) with the changes if you already have something built.

I'm going to close this issue, but don't hesitate to open another if you find it's still persisting.
