### ISSUE TITLE
now working redux

### ISSUE THREAD

**Issue by marshallcool** [cullenjett/react-ssr-boilerplate#8]
Console does not display actions, redux devtools does not connect to store, npm i -> npm star

**Comment by cullenjett** [comment]
Redux dev tools isn't set up for this project so you'll need to do it. You can find the Redux store configuration in `src/configureStore.js`, that's probably where you'll need to add some code.

Re: actions not logging in the browser console -- they seem to be working for me (at least on `2.10.0`, the most recent version). The sample code doesn't actually dispatch any client-side actions, only one on the server, inside the `static fetchData()` method on the `<Home />` component. If you'd like to see actions logged on the server (ie in the terminal) you can change line 15 of `server/renderServerSideApp.js` to set `logger: true`.

Here's the quick and dirty way I verified the client-side action logging is working. This is inside `src/components/About.js`:

```diff
    import React, { Component } from 'react';
+   import PropTypes from 'prop-types';
+   import { connect } from 'react-redux';

    import { imagePath } from '../../utils/assetUtils';
    import styles from './about.scss';

    class About extends Component {
+     static propTypes = {
+       doSomething: PropTypes.func
+     };

      render() {
        return (
          <div>
            <h1 className={styles.title}>About page</h1>
+           <button onClick={this.props.doSomething}>Do something</button>
            <img className={styles.reactLogo} src={imagePath('react.svg')} alt="" />
          </div>
        );
      }
    }

-  export default About;
+  export default connect(
+    null,
+    dispatch => ({
+      doSomething: () => dispatch({ type: 'CONSOLE_LOG_TEST ' })
+    })
+  )(About);
```

Clicking the button shows the logs in the browser console.

**Comment by nimahkh** [comment]
here i have an update package with redux , you can find it here 
https://github.com/nimahkh/react-easy-boilerplates
